Change logos and update menu
bindworks/zScanner-Plzen-iOS pull request #12
Opened 2020-02-26 13:06 UTC by Finemas

Changed the IKEM logo for the Medicalc one and changed colors of the menu.

2020-02-27 21:08 UTC, skorepak requested changes
Minor comment added

2020-02-27 21:08 UTC, skorepak commented on zScanner/ViewControllers/About/AboutViewController.swift
> +//        imageView.backgroundColor = .white
Remove commented code

2020-02-28 10:18 UTC, Finemas commented
The Medicalc logo on the launch screen is not visible.

2020-02-28 10:33 UTC, skorepak approved these changes

2020-02-28 10:37 UTC, merged